name: example_localization
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  # get:
  easy_localization: ^3.0.5
  go_router: ^15.1.2

  # 🗃️ Local database
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.3

  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  workmanager: ^0.5.2
  audioplayers: ^5.2.1
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # ⚙️ Required for Isar code generation
  isar_generator: ^3.1.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
  generate: true